services:
  - type: web
    name: task-management-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PORT
        value: 5555
